---

- name: Define pool
  command: "virsh pool-define-as {{ pool.name }} {{ pool.type }} - - {{ pool.device_path }} {{ pool.vol_group }} {{ pool.path }}"
  register: output
  failed_when:
  - "output.stderr != ''"
  - "'already exists' not in output.stderr"
  changed_when: "'already exists' not in output.stderr"

- name: Build pool
  command: "virsh pool-build {{ pool.name }}"
  register: output
  failed_when:
  - "output.stderr != ''"
  - "'already active' not in output.stderr"
  changed_when: "'already active' not in output.stderr"

- name: Start pool
  command: "virsh pool-start {{ pool.name }}"
  register: output
  failed_when: 
  - "output.stderr != ''"
  - "'already active' not in output.stderr"
  changed_when: "'already active' not in output.stderr"

- name: Set pool to autostart
  command: "virsh pool-autostart {{ pool.name }}"
